# Generated by Django 5.2 on 2025-04-07 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
