# Generated by Django 5.2 on 2025-04-10 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0003_alter_appointment_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='created_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name__in': ['PA', 'SECRETARY']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='regularvisitor',
            name='created_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name__in': ['PA', 'SECRETARY']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
