# Generated by Django 5.2 on 2025-04-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0004_alter_appointment_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularvisitor',
            name='v_type',
            field=models.CharField(blank=True, default='outside', max_length=100, null=True),
        ),
    ]
