# Generated by Django 5.2 on 2025-04-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0005_alter_regularvisitor_v_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='v_type',
            field=models.CharField(blank=True, default='OUTSIDE', max_length=100, null=True),
        ),
    ]
