# Generated by Django 5.2 on 2025-04-18 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0007_appointment_gm'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secretary',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'SECRETARY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretary_tag', to=settings.AUTH_USER_MODEL),
        ),
    ]
