# Generated by Django 5.2 on 2025-04-18 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0008_user_secretary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gm',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'GM'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gm_tag', to=settings.AUTH_USER_MODEL),
        ),
    ]
