# Generated by Django 5.2 on 2025-04-18 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0009_alter_user_gm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'SECRETARY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_appointments', to=settings.AUTH_USER_MODEL),
        ),
    ]
