# Generated by Django 5.2 on 2025-04-21 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0011_alter_appointment_purpose_of_visit'),
    ]

    operations = [
        migrations.CreateModel(
            name='GMTraffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('gm', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'GM'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gm_traffic', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gm_traffic',
            },
        ),
    ]
